import { displayRoleName } from '../../lib/roles'
import { ArrowRight, Database, Fingerprint, RefreshCw, ScanText, ShieldCheck } from 'lucide-react'
import type { SessionUser } from '../auth/session'
import { useHealth } from '../../hooks/useHealth'
import { AccountProvisioning } from './AccountProvisioning'
import { AdminRequests } from './AdminRequests'
import './settings.css'

type Props = { user: SessionUser; expiresAt: string; token: string }

export function SettingsPage({ user, expiresAt, token }: Props) {
  const { state, retry } = useHealth()
  const expiry = new Date(expiresAt)
  const provider = state.phase === 'ready' ? state.data.provider as typeof state.data.provider & { pdfTextAvailable?: boolean; ocrAvailable?: boolean; installedLanguages?: string[]; unsupportedLanguages?: string[] } : null

  return <section className="p5-settings">
    <header className="p5-settings-header"><div><span className="p5-settings-eyebrow">Account and services</span><h1>Settings</h1><p>Review your authenticated account, service availability, and data boundaries.</p></div><span className="p5-settings-header-icon"><Fingerprint size={23} aria-hidden="true" /></span></header>

    <div className="p5-settings-grid">
      <section className="p5-settings-panel" aria-labelledby="p5-settings-role-title"><div className="p5-settings-section-heading"><span className="p5-settings-eyebrow">Server-issued session</span><h2 id="p5-settings-role-title">Your account</h2></div><div className="p5-settings-current"><span className="p5-settings-avatar" aria-hidden="true">{user.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><div><strong>{user.name}</strong><span>{user.email} · {displayRoleName(user.role)}</span></div><ShieldCheck size={19} aria-hidden="true" /></div><p className="p5-settings-copy">The API identifies you from the signed session and enforces permissions on each protected request. Field edits and decisions are attributed to your account in the audit trail.</p><div className="p5-settings-expiry">Session expires <strong>{Number.isNaN(expiry.getTime()) ? 'at an unknown time' : expiry.toLocaleString()}</strong></div><h3>Account access</h3>{user.requestedRole === 'ADMIN' && user.roleApprovalStatus === 'PENDING' ? <p className="p5-settings-copy p5-settings-role-pending">Administrator access requested · pending approval. Your current access is read-only Auditor.</p> : user.requestedRole === 'ADMIN' && user.roleApprovalStatus === 'REJECTED' ? <p className="p5-settings-copy">Your administrator request was not approved. Your current access is read-only Auditor.</p> : <p className="p5-settings-copy">Your available actions follow the role assigned by the service. Contact an administrator if your access needs to change.</p>}</section>

      <section className="p5-settings-panel" aria-labelledby="p5-settings-health-title"><div className="p5-settings-section-heading"><span className="p5-settings-eyebrow">Operational status</span><h2 id="p5-settings-health-title">Local services</h2></div>{state.phase === 'loading' ? <p className="p5-settings-copy" role="status">Checking the API and processing provider…</p> : null}{state.phase === 'error' ? <div className="p5-settings-error" role="alert"><strong>Service status unavailable</strong><span>{state.message}</span><button type="button" onClick={retry}><RefreshCw size={14} aria-hidden="true" />Retry check</button></div> : null}{state.phase === 'ready' ? <><div className="p5-settings-health-line"><span className={state.data.status === 'ok' ? 'p5-settings-health-dot' : 'p5-settings-health-dot p5-settings-health-dot--error'} /><div><strong>{state.data.status === 'ok' ? 'API responding' : `API: ${state.data.status}`}</strong><small>{state.data.service} · version {state.data.version}</small></div><button type="button" onClick={retry} aria-label="Refresh service status"><RefreshCw size={15} aria-hidden="true" /></button></div><dl className="p5-settings-facts"><div><dt>Environment</dt><dd>{state.data.environment}</dd></div><div><dt>Text extraction</dt><dd>{provider?.provider}</dd></div><div><dt>Embedded PDF text</dt><dd>{provider?.pdfTextAvailable ? 'Available' : 'Unavailable'}</dd></div><div><dt>Image OCR</dt><dd>{provider?.ocrAvailable ? 'Available' : 'Unavailable'}</dd></div><div><dt>Installed OCR languages</dt><dd>{provider?.installedLanguages?.join(', ') || 'None detected'}</dd></div></dl>{provider?.unsupportedLanguages?.length ? <p className="p5-settings-copy">Unsupported requested OCR languages: {provider.unsupportedLanguages.join(', ')}.</p> : null}{provider?.message ? <p className="p5-settings-copy">{provider.message}</p> : null}</> : null}<div className="p5-settings-divider" /><div className="p5-settings-next"><ScanText size={19} aria-hidden="true" /><div><strong>{user.role === 'ADMIN' || user.role === 'REVENUE_OFFICER' ? 'Process a source document' : 'Inspect source documents'}</strong><span>{user.role === 'ADMIN' || user.role === 'REVENUE_OFFICER' ? 'Upload a PDF or image. Progress and results come from the persisted processing pipeline.' : 'Read document evidence and processing results within your assigned permissions.'}</span><a href="#/documents">Open documents <ArrowRight size={14} aria-hidden="true" /></a></div></div></section>
    </div>

    {user.role === 'ADMIN' ? <><AdminRequests token={token} /><AccountProvisioning token={token} /></> : null}
    <section className="p5-settings-boundaries" aria-labelledby="p5-settings-boundaries-title"><div><Database size={18} aria-hidden="true" /><h2 id="p5-settings-boundaries-title">Product boundaries</h2></div><dl><div><dt>Functional workflow</dt><dd>Authenticated upload, text extraction or OCR, field extraction, validation, human review, attributed audit, and record-linked GIS views.</dd></div><div><dt>Synthetic development data</dt><dd>Test fixtures and local seed records are labeled as synthetic development data. Uploaded documents use the same processing path.</dd></div><div><dt>External integrations</dt><dd>Official land registries, cadastral geometry, and a production identity provider require integration with authoritative services.</dd></div></dl><p>AI assists. Validation checks. Human officers verify. This prototype does not determine legal ownership.</p></section>
  </section>
}
