import { useReducedMotion } from 'framer-motion'
import { Activity, CircleAlert, Database, RefreshCw, ShieldCheck } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { formatCount, formatPercent, operationLabel, readableDate, useAnalytics, type AnalyticsSummary } from '../dashboard/operationsData'

const panel = 'min-w-0 rounded-xl border border-[var(--bd-border)] bg-white shadow-[var(--bd-shadow-sm)]'

function Metrics({ summary }: { summary: AnalyticsSummary }) {
  const m = summary.metrics
  const cells = [
    { label: 'Documents processed', value: formatCount(m.documentsProcessed), detail: `${formatCount(m.documentsTotal)} source documents received` },
    { label: 'Approval rate', value: formatPercent(m.approvalRate), detail: 'Latest approved / decided reviews' },
    { label: 'Review rate', value: formatPercent(m.reviewRate), detail: 'Cases routed to human review' },
    { label: 'Conflict rate', value: formatPercent(m.conflictRate), detail: 'Processed documents with conflicts' },
    { label: 'Average quality score', value: m.averageQualityScore === null ? '—' : `${Math.round(m.averageQualityScore * 10) / 10} / 100`, detail: 'Across scored processed records' },
  ]
  return <div className="grid grid-cols-2 gap-3 xl:grid-cols-5">{cells.map((item, index) => <div className={`${panel} ${index === cells.length - 1 ? 'col-span-2 xl:col-span-1' : ''} flex min-h-[133px] flex-col justify-between border-t-[3px] border-t-[var(--bd-info)] p-4`} key={item.label}><span className="text-[11px] font-semibold text-[var(--bd-text-muted)]">{item.label}</span><strong className="text-[clamp(1.45rem,2vw,1.9rem)] font-semibold tracking-[-.05em] tabular-nums text-[var(--bd-text)]">{item.value}</strong><small className="text-[10px] leading-4 text-[var(--bd-text-subtle)]">{item.detail}</small></div>)}</div>
}

function ProcessingVolume({ summary, reducedMotion }: { summary: AnalyticsSummary; reducedMotion: boolean }) {
  const data = summary.processingVolume.map((item) => ({ ...item, label: new Date(`${item.date}T00:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }))
  return <section className={`${panel} overflow-hidden`} aria-label="Processing volume over time">
    <div className="border-b border-[var(--bd-border)] px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--bd-text-subtle)]">Activity</p><h2 className="mt-1 text-[15px] font-semibold text-[var(--bd-text)]">Processing volume over time</h2><p className="mt-1 text-[11px] text-[var(--bd-text-muted)]">Completed document processing runs by date</p></div>
    {data.length === 0 || data.every((item) => item.count === 0) ? <div className="flex min-h-[240px] flex-col items-center justify-center gap-2 px-6 text-center"><Activity size={23} className="text-[var(--bd-info)]" aria-hidden="true" /><strong className="text-sm text-[var(--bd-text)]">No processing volume yet</strong><p className="text-xs text-[var(--bd-text-muted)]">Process a source document to populate this chart.</p></div> : <div className="px-3 pb-4 pt-5 sm:px-5"><div role="img" aria-label={`Processed documents by day: ${data.map((item) => `${item.label} ${item.count}`).join(', ')}`} className="h-[250px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 8, right: 6, bottom: 0, left: -24 }} accessibilityLayer><defs><linearGradient id="analytics-volume-gradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#286c90" stopOpacity={0.22} /><stop offset="100%" stopColor="#286c90" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9efed" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#647982', fontSize: 10 }} dy={8} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: '#647982', fontSize: 10 }} /><Tooltip contentStyle={{ border: '1px solid #dce7e2', borderRadius: 8, fontSize: 11 }} /><Area type="monotone" dataKey="count" name="Processed" stroke="#286c90" strokeWidth={2.5} fill="url(#analytics-volume-gradient)" isAnimationActive={!reducedMotion} /></AreaChart></ResponsiveContainer></div></div>}
  </section>
}

function Distribution({ title, subtitle, items }: { title: string; subtitle: string; items: { status: string; count: number }[] }) {
  const total = items.reduce((value, item) => value + item.count, 0)
  const color = (status: string) => /conflict|reject|fail/i.test(status) ? 'bg-[var(--bd-danger)]' : /review|warning|processing|pending/i.test(status) ? 'bg-[var(--bd-warning)]' : /approv|valid|pass|clear|complete/i.test(status) ? 'bg-[var(--bd-success)]' : 'bg-[var(--bd-info)]'
  return <section className={`${panel} overflow-hidden`} aria-label={title}><div className="border-b border-[var(--bd-border)] px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--bd-text-subtle)]">Distribution</p><h2 className="mt-1 text-[15px] font-semibold text-[var(--bd-text)]">{title}</h2><p className="mt-1 text-[11px] text-[var(--bd-text-muted)]">{subtitle}</p></div>{total === 0 ? <div className="flex min-h-[195px] flex-col items-center justify-center px-6 text-center"><Database size={22} className="text-[var(--bd-info)]" aria-hidden="true" /><p className="mt-3 text-xs text-[var(--bd-text-muted)]">No results in this distribution yet.</p></div> : <div className="space-y-4 px-5 py-5">{items.filter((item) => item.count > 0).map((item) => <div key={item.status}><div className="mb-1.5 flex items-baseline justify-between gap-3 text-[11px]"><span className="font-medium text-[var(--bd-text-muted)]">{operationLabel(item.status)}</span><strong className="tabular-nums text-[var(--bd-text)]">{formatCount(item.count)} <span className="font-medium text-[var(--bd-text-subtle)]">({Math.round(item.count / total * 100)}%)</span></strong></div><div role="progressbar" aria-label={operationLabel(item.status)} aria-valuenow={item.count} aria-valuemin={0} aria-valuemax={total} className="h-2 rounded-full bg-[#edf1ef]"><div className={`h-full rounded-full ${color(item.status)}`} style={{ width: `${item.count / total * 100}%` }} /></div></div>)}</div>}</section>
}

export function AnalyticsPage({ token }: { token: string }) {
  const reducedMotion = Boolean(useReducedMotion())
  const { state, retry } = useAnalytics(token)
  return <div className="mx-auto w-full max-w-[1450px] space-y-5 pb-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[var(--bd-accent)]">Measured workflow</p><h1 className="mt-1 text-[clamp(1.7rem,2.5vw,2.2rem)] font-semibold tracking-[-.04em] text-[var(--bd-text)]">Operational analytics</h1><p className="mt-1.5 text-[13px] text-[var(--bd-text-muted)]">Understand processing, validation, and officer review across persisted prototype data.</p></div><button type="button" onClick={retry} className="inline-flex min-h-9 items-center gap-1.5 rounded-md border border-[var(--bd-border-strong)] bg-white px-3 text-xs font-semibold text-[var(--bd-text-muted)] hover:bg-[var(--bd-surface-muted)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--bd-info)]"><RefreshCw size={14} aria-hidden="true" />Refresh</button></header>
    {state.phase === 'loading' && <div role="status" className="space-y-4"><span className="sr-only">Loading operational analytics</span><div className="h-16 rounded-xl bg-[#e9efec] motion-safe:animate-pulse" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-36 rounded-xl bg-[#e9efec] motion-safe:animate-pulse" />)}</div><div className="h-72 rounded-xl bg-[#e9efec] motion-safe:animate-pulse" /></div>}
    {state.phase === 'error' && <div role="alert" className="rounded-xl border border-[#edceca] bg-[#fff8f6] p-6"><p className="flex items-center gap-2 font-semibold text-[var(--bd-danger)]"><CircleAlert size={18} aria-hidden="true" />Analytics unavailable</p><p className="mt-2 text-sm text-[var(--bd-text-muted)]">{state.error}</p><button type="button" onClick={retry} className="mt-4 rounded-md bg-[var(--bd-accent)] px-3 py-2 text-xs font-semibold text-white">Retry</button></div>}
    {state.phase === 'ready' && <><div role="note" className="flex items-start gap-2 rounded-lg border border-[#d6e5df] bg-[#f1f7f3] px-4 py-3 text-[11px] leading-5 text-[#3f6b59]"><ShieldCheck size={16} className="mt-0.5 shrink-0" aria-hidden="true" /><span><strong>Prototype workflow data.</strong> {state.data.disclaimer} Generated {readableDate(state.data.generatedAt)}.</span></div><Metrics summary={state.data} /><ProcessingVolume summary={state.data} reducedMotion={reducedMotion} /><div className="grid gap-4 lg:grid-cols-2"><Distribution title="Validation distribution" subtitle="How processed documents were routed" items={state.data.validationDistribution} /><Distribution title="Processing status" subtitle="Current state of uploaded source documents" items={state.data.processingStatusDistribution} /></div><div className="rounded-lg border border-[var(--bd-border)] bg-white px-5 py-4 text-[11px] leading-5 text-[var(--bd-text-muted)]"><strong className="text-[var(--bd-text)]">How rates are calculated</strong><ul className="mt-2 list-inside list-disc space-y-1"><li>Approval rate: {state.data.definitions.approvalRate}</li><li>Review rate: {state.data.definitions.reviewRate}</li><li>Conflict rate: {state.data.definitions.conflictRate}</li></ul></div><p className="border-t border-[var(--bd-border)] pt-4 text-[11px] leading-5 text-[var(--bd-text-subtle)]">These are local prototype measurements, not statistics from a government program or production deployment. AI-assisted extraction supports human verification.</p></>}
  </div>
}
