"""phase4 review audit gis

Revision ID: 0003_phase4
Revises: 0002_documents
Create Date: 2026-09-24 23:30:50.536296
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003_phase4'
down_revision: Union[str, None] = '0002_documents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('parcel_index',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('record_number', sa.String(length=128), nullable=True),
    sa.Column('survey_number', sa.String(length=128), nullable=True),
    sa.Column('owner_name', sa.String(length=256), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.Column('geometry_source', sa.String(length=32), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    with op.batch_alter_table('parcel_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcel_index_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcel_index_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcel_index_owner_name'), ['owner_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcel_index_record_number'), ['record_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcel_index_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcel_index_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcel_index_survey_number'), ['survey_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcel_index_village'), ['village'], unique=False)

    op.create_table('review_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('priority_reasons', sa.JSON(), nullable=False),
    sa.Column('assigned_officer_id', sa.String(length=64), nullable=True),
    sa.Column('original_record', sa.JSON(), nullable=False),
    sa.Column('reviewed_record', sa.JSON(), nullable=False),
    sa.Column('field_reviews', sa.JSON(), nullable=False),
    sa.Column('issue_resolutions', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('primary_conflict', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decision_reason', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_cases_assigned_officer_id'), ['assigned_officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_record_id'), ['record_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_review_cases_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cases_status'))
        batch_op.drop_index(batch_op.f('ix_review_cases_record_id'))
        batch_op.drop_index(batch_op.f('ix_review_cases_priority'))
        batch_op.drop_index(batch_op.f('ix_review_cases_document_id'))
        batch_op.drop_index(batch_op.f('ix_review_cases_assigned_officer_id'))

    op.drop_table('review_cases')
    with op.batch_alter_table('parcel_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcel_index_village'))
        batch_op.drop_index(batch_op.f('ix_parcel_index_survey_number'))
        batch_op.drop_index(batch_op.f('ix_parcel_index_status'))
        batch_op.drop_index(batch_op.f('ix_parcel_index_state'))
        batch_op.drop_index(batch_op.f('ix_parcel_index_record_number'))
        batch_op.drop_index(batch_op.f('ix_parcel_index_owner_name'))
        batch_op.drop_index(batch_op.f('ix_parcel_index_document_id'))
        batch_op.drop_index(batch_op.f('ix_parcel_index_district'))

    op.drop_table('parcel_index')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_events_record_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_document_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
