"""allow review attempts

Revision ID: 0004_review_attempts
Revises: 0003_phase4
Create Date: 2026-09-24 23:32:00.217056
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004_review_attempts'
down_revision: Union[str, None] = '0003_phase4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cases_record_id'))
        batch_op.create_index(batch_op.f('ix_review_cases_record_id'), ['record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cases_record_id'))
        batch_op.create_index(batch_op.f('ix_review_cases_record_id'), ['record_id'], unique=1)

    # ### end Alembic commands ###
